#
# Jekyll configuration
#
#destination: ./_site
auto:        false
lsi:         true # better related posts
server_port: 4000
pygments:    true
markdown:    maruku
permalink:   none
maruku:
  use_tex:    true
  use_divs:   false
  png_dir:    /assets/img
  png_url:    /assets/img

#
# Site configuration
#
url:          http://localhost:4000
title:        Amitava's Technical Blog
description:  Technical articles worth sharing
keywords:     linux kvm qemu haskell ruby javascript architecture medschool 
author:       Amitava Shee
email:        amitava.shee@gmail.com
analytics_id: UA-3575874-3
