# Site settings
title: Amitava Shee
email: amitava.shee@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is Amitava Shee's blog to record and share his discoveries
  in technology and architecture. Amitava is a programmer and a systems
  architect building applications and integration solutions in the healthcare
  research domain for over 20 years.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ashee.github.com" # the base hostname & protocol for your site
twitter_username: amitavashee
github_username:  ashee
linkedin_username: amitavashee
ga_tracking_id: "UA-71417845-1"

# Build settings
markdown: kramdown
